### ISSUE TITLE
Delete direct messages?

### ISSUE THREAD

**Issue by chaoscreater** [etnepres/slack-deleter-userscript#1]
Hi there,

Does this only work for channels, or does it work for direct message too? Is it possible to remove all of your own messages from everything? Or do we have to constantly edit the channel URL to a different one?

Also, I get the popup asking me if I want to delete the message, but it doens't actually delete it?

**Comment by etnepres** [comment]
Should work for messages too but seems to need a bug fix after last slack update. Will do that later today after work.

**Comment by etnepres** [comment]
Hi @chaoscreater 

Thank you again for letting me know of the problem, it should work now, instructions also updated.
